apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: sbm-nginx
spec:
  containers:
  - name: sbm-nginx
    image: tuncerkaraarslan/sbm-nginx-app-2:0.2
    ports:
    - containerPort: 80
