apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: sbm-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # Belirli bir NodePort tanımlaması
  type: NodePort


